### ISSUE TITLE
is it possible to minimize the toolbox requirements? 

### ISSUE THREAD

**Issue by alexlib** [jonnyhigham/PTVResearch#1]
Hi, 
I couldn't install the app as it requires several toolboxes. Could you please write which ones are necessary and whether it's possible to install without some?

**Comment by jonnyhigham** [comment]
At the moment the app requires the image processing toolbox and the computer vision toolbox. It is possible to write the scripts outside of the toolboxes, but Matlab does a very good job of speeding them up (people might think I was crazy saying that 5 years ago!). 

I do have plans to port the OpenCV toolboxes into Matlab and this would get around this problem, but it is still early days. The initial concept of the App was actually to help some colleagues out at UCL creating a fully contained app they could use with minimal programming knowledge.

**Comment by alexlib** [comment]
I see, thanks.
